version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/one"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "nodemon"
      - dependency-name: "supertest"
      - dependency-name: "tape"
  - package-ecosystem: "npm"
    directory: "/two"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "nodemon"
      - dependency-name: "supertest"
      - dependency-name: "tape"
  - package-ecosystem: "npm"
    directory: "/three"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "nodemon"
      - dependency-name: "supertest"
      - dependency-name: "tape" 
  - package-ecosystem: "npm"
    directory: "/four"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "nodemon"
      - dependency-name: "supertest"
      - dependency-name: "tape" 
  - package-ecosystem: "npm"
    directory: "/five"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "nodemon"
      - dependency-name: "supertest"
      - dependency-name: "tape"  
